# Generated by Django 6.0.4 on 2026-04-26 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_q1', models.TextField(db_column='q1')),
                ('_q2', models.TextField(db_column='q2')),
                ('_q3', models.TextField(db_column='q3')),
                ('_q4', models.TextField(db_column='q4')),
                ('_q5', models.TextField(db_column='q5')),
                ('_q6', models.TextField(db_column='q6')),
                ('_q7', models.TextField(db_column='q7')),
                ('_q8', models.TextField(db_column='q8')),
                ('_text1', models.TextField(blank=True, db_column='text1', null=True)),
                ('_text2', models.TextField(blank=True, db_column='text2', null=True)),
                ('_text3', models.TextField(blank=True, db_column='text3', null=True)),
                ('_text4', models.TextField(blank=True, db_column='text4', null=True)),
                ('_text5', models.TextField(blank=True, db_column='text5', null=True)),
                ('_text6', models.TextField(blank=True, db_column='text6', null=True)),
                ('_text7', models.TextField(blank=True, db_column='text7', null=True)),
                ('_text8', models.TextField(blank=True, db_column='text8', null=True)),
                ('total_score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
